// export { default as coffeeBag } from "../../src/assets/images/coffee_bag.svg";
export { default as CoffeeBag } from "../../src/assets/images/coffee_bag.svg?react";
export { default as CoffeeBag2 } from "../../src/assets/images/coffee_bag_2.svg?react";
// export { default as coffeeBag3 } from "../../src/assets/images/coffee_bag.png";
// export { default as coffeeBag4 } from "../../src/assets/images/coffee_bag1.png";
//export svg here
export { default as DesignCard } from "../../src/assets/images/design-card.svg?react";
export { default as Cross } from "../assets/images/cross.svg?react";
export { default as DesignCard2 } from "../../src/assets/images/design-card2.svg?react";
export { default as ShowCaseBag } from "../../src/assets/images/showcase-bag.svg?react";
export { default as PaintIcon } from "../../src/assets/images/paint.svg?react";
export { default as AeroPlaneIcon } from "../../src/assets/images/aeroplane.svg?react";
export { default as Logo } from "../../src/assets/images/logo.svg?react";
export { default as Customize } from "../assets/images/customization.svg?react";
export { default as Delivery } from "../assets/images/delivery.svg?react";
export { default as Europe } from "../assets/images/european-union.svg?react";
export { default as Return } from "../assets/images/return-policy.svg?react";
export { default as Sustain } from "../assets/images/sustainable.svg?react";
// export png here
export { default as bg1 } from "../../src/assets/images/banner1.png";
export { default as banner_bg2 } from "../../src/assets/images/banner_bg2.png";
export { default as demoReview1 } from "../../src/assets/images/review-demo1.png";
export { default as demoReview3 } from "../assets/images/review-demo3.png";
export { default as company1 } from "../assets/images/company1.png";
export { default as company2 } from "../assets/images/company2.png";
export { default as coffeeBag } from "..//assets/images/coffee_bag.webp";
export { default as testPrint } from "../assets/images/test-print.png";
export { default as Preview3D } from "../assets/images/3d-preview.png";
export { default as designSupport } from "../assets/images/design-support.png";
export { default as heroBg } from "../assets/images/hero_bg.webp";
export { default as banner1_mobile } from "../assets/images/banner-mobile1.png";
export { default as banner2_mobile } from "../assets/images/banner_mb_bg2.png";

export { default as designPattern2 } from "../assets/images/design-pattern2.png";
export { default as designCard1 } from "../assets/images/design-card1.png";
export { default as designCard2 } from "../assets/images/design-card2.png";

export { default as menuIcon } from "../assets/images/menu-icon.svg";
export { default as menuClose } from "../assets/images/menu-close.svg";
export { default as plusIcon } from "../assets/images/plus-Icon.svg";

export { default as supprotIcon } from "../assets/images/supprotIcon.png";

export { default as testPrintIcon } from "../assets/images/testPrintIcon.png";

export { default as configIcon } from "../assets/images/configIcon.png";

export { default as Preview3DIcon } from "../assets/images/preview3DIcon.png";
export { default as cupImage3DIcon } from "../assets/images/cup-image.png";
export { default as packetImage } from "../assets/images/packet-image.png";
export { default as commentIcon} from "../assets/images/comment-icon.svg";
export { default as starFaceEmoji} from "../assets/images/star-face-emoji.png";
export { default as packetActiveIcon} from "../assets/images/packet-active-icon.svg";
export { default as packetIcon} from "../assets/images/packet-icon.svg";
export { default as productFrame} from "../assets/images/product-frame.png";
export { default as customizeComputer} from "../assets/images/customize-computer.svg";
export { default as packetStatsIcon} from "../assets/images/packet-stats-icon.svg";
export { default as cartonBoxIcon} from "../assets/images/carton-box-icon.svg";
export { default as cartonBoxActiveIcon} from "../assets/images/carton-box-active-icon.svg";
export { default as sideGussetBagsIcon} from "../assets/images/side-gusset-bags-icon.svg";
export { default as sideGussetBagsActiveIcon} from "../assets/images/side-gusset-bags-active-icon.svg";
export { default as standupBagsIcon} from "../assets/images/standup-bags-icon.svg";
export { default as standupBagsActiveIcon} from "../assets/images/standup-bags-active-icon.svg";
export { default as europeanUnionSmall} from "../assets/images/european-union-small.svg";
export { default as mugHotAltIcon} from "../assets/images/mug-hot-alt-icon.svg";
export { default as shieldCheckIcon} from "../assets/images/shield-check-icon.svg";
export { default as pickingBoxIcon} from "../assets/images/picking-box-icon.svg";
export { default as materialCardImageOne} from "../assets/images/material-card-image-1.png";
export { default as materialCardImageTwo} from "../assets/images/material-card-image-2.png";
export { default as matteIcon} from "../assets/images/matte-icon.svg";
export { default as premiumMatteIcon} from "../assets/images/premium-matte-icon.svg";
export { default as softTouchIcon} from "../assets/images/soft-touch-icon.svg";
export { default as sandyTouchIcon} from "../assets/images/sandy-touch-icon.svg";
export { default as oxygenIcon} from "../assets/images/oxygen-icon.svg";
export { default as humidityIcon} from "../assets/images/humidity-icon.svg";
export { default as uvLightIcon} from "../assets/images/uv-light-icon.svg";
export { default as twoCtaCardOne} from "../assets/images/two-cta-card-1.png";
export { default as twoCtaCardTwo} from "../assets/images/two-cta-card-2.png";
export { default as matteCoffeeBagImage} from "../assets/images/matte-coffee-bag-image.png";
export { default as matteCoffeeBagImageTwo} from "../assets/images/matte-coffee-bag-image-two.png";
export { default as matteCoffeeBagImageThree} from "../assets/images/matte-coffee-bag-image-three.png";
export { default as servicesHeroImage} from "../assets/images/services-hero-image.png";
export { default as servicesHeroMobileImage} from "../assets/images/services-hero-mobile-image.png";
export { default as dripBagsActiveIcon} from "../assets/images/drip-bags-active-icon.svg";
export { default as dripBagsIcon} from "../assets/images/drip-bags-icon.svg";
export { default as brewBagIcon} from "../assets/images/brew-bag-icon.svg";
export { default as brewBagActiveIcon} from "../assets/images/brew-bag-active-icon.svg";
export { default as capsulesIcon} from "../assets/images/capsules-icon.svg";
export { default as capsulesActiveIcon} from "../assets/images/capsules-active-icon.svg";
export { default as coffeeIcon} from "../assets/images/coffee-icon.svg";
export { default as subscriptionIcon} from "../assets/images/subscription-icon.svg";
export { default as officesImage} from "../assets/images/offices-image.png";
export { default as chairOfficeIcon} from "../assets/images/chair-office-icon.svg";
export { default as chairOfficeActiveIcon} from "../assets/images/chair-office-active-icon.svg";
export { default as gasPumpIcon} from "../assets/images/gas-pump-icon.svg";
export { default as gasPumpActiveIcon} from "../assets/images/gas-pump-active-icon.svg";
export { default as houseTreeIcon} from "../assets/images/house-tree-icon.svg";
export { default as houseTreeActiveIcon} from "../assets/images/house-tree-active-icon.svg";
export { default as dormRoomIcon} from "../assets/images/dorm-room-icon.svg";
export { default as dormRoomActiveIcon} from "../assets/images/dorm-room-active-icon.svg";
export { default as shoppingCartIcon} from "../assets/images/shopping-cart-icon.svg";
export { default as shoppingCartActiveIcon} from "../assets/images/shopping-cart-active-icon.svg";
export { default as calendarStarIcon} from "../assets/images/calendar-star-icon.svg";
export { default as calendarStarActiveIcon} from "../assets/images/calendar-star-active-icon.svg";
export { default as giftIcon} from "../assets/images/gift-icon.svg";
export { default as giftActiveIcon} from "../assets/images/gift-active-icon.svg";
export { default as gasStationsImage} from "../assets/images/gas-stations-image.png";
export { default as touristShopsImage} from "../assets/images/tourist-shops-image.png";
export { default as hotelsImage} from "../assets/images/hotels-image.png";
export { default as onlineStoresImage} from "../assets/images/online-stores-image.png";
export { default as eventsAndConferencesImage} from "../assets/images/events-and-conferences-image.png";
export { default as giftShopsImage} from "../assets/images/gift-shops-image.png";
export { default as servicesCtaImage} from "../assets/images/services-cta-image.png";
export { default as coffeeBeansIcon} from "../assets/images/coffee-beans-icon.svg";
export { default as envelopePapperIcon} from "../assets/images/envelope-papper-icon.svg";
export { default as coffeeHeartIcon} from "../assets/images/coffee-heart-icon.svg";
export { default as personVectorIcon} from "../assets/images/person-vector-icon.svg";
export { default as dripBagMainImage} from "../assets/images/drip-bag-main-image.png";
export { default as dripCardImageOne} from "../assets/images/drip-card-image-one.png";
export { default as dripCardImageTwo} from "../assets/images/drip-card-image-two.png";
export { default as threeSixtyIcon} from "../assets/images/360-icon.svg";
export { default as fireEmojiIcon} from "../assets/images/fire-emoji-icon.png";
